//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_Organizer_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toplanti
    {
        public int toplanti_id { get; set; }
        public string toplanti_konusu { get; set; }
        public string tarih { get; set; }
        public string bas_saati { get; set; }
        public string bit_saati { get; set; }
        public string katilimcilar { get; set; }
    }
}
